#!/bin/bash

#host only network parameters
sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=0/g' /etc/sysctl.conf
sed -i 's/#net.ipv4.conf.all.send_redirects = 1/net.ipv4.conf.all.send_redirects = 0/g' /etc/sysctl.conf
sed -i 's/#net.ipv4.conf.all.accept_redirects = 1/net.ipv4.conf.all.accept_redirects = 0/g' /etc/sysctl.conf
sed -i 's/#net.ipv4.conf.all.secure_redirects = 1/net.ipv4.conf.all.secure_redirects = 0/g' /etc/sysctl.conf
sed -i 's/#net.ipv4.conf.all.log_martians = 0/net.ipv4.conf.all.log_martians = 1/g' /etc/sysctl.conf
sed -i 's/#net.ipv4.conf.all.rp_filter=0/net.ipv4.conf.all.rp_filter=1/g' /etc/sysctl.conf
sed -i 's/#net.ipv4.tcp_syncookies=0/net.ipv4.tcp_syncookies=1/g' /etc/sysctl.conf
sed -i 's/#net.ipv6.conf.all.accept_redirects = 1/net.ipv6.conf.all.accept_redirects = 0/g' /etc/sysctl.conf
echo "net.ipv4.conf.all.send_redirects = 0" >> /etc/sysctl.conf
echo "net.ipv4.conf.all.accept_source_route = 0" >> /etc/sysctl.conf
echo "net.ipv4.conf.default.accept_source_route = 0" >> /etc/sysctl.conf
echo "net.ipv4.conf.default.accept_redirects = 0" >> /etc/sysctl.conf
echo "net.ipv4.conf.default.secure_redirects = 0" >> /etc/sysctl.conf
echo "net.ipv4.conf.default.log_martians = 1" >> /etc/sysctl.conf
echo "net.ipv4.icmp_echo_ignore_broadcasts = 1" >> /etc/sysctl.conf
echo "net.ipv4.icmp_ignore_bogus_error_responses = 1" >> /etc/sysctl.conf
echo "net.ipv4.conf.default.rp_filter=1" >> /etc/sysctl.conf
echo "net.ipv6.conf.all.accept_ra = 0" >> /etc/sysctl.conf
echo "net.ipv6.conf.default.accept_ra = 0" >> /etc/sysctl.conf
echo "net.ipv6.conf.default.accept_redirects = 0" >> /etc/sysctl.conf
sysctl -w net.ipv4.ip_forward=0
sysctl -w net.ipv4.conf.all.send_redirects=0
sysctl -w net.ipv4.conf.default.send_redirects=0
sysctl -w net.ipv4.conf.all.accept_source_route=0
sysctl -w net.ipv4.conf.default.accept_source_route=0
sysctl -w net.ipv4.conf.all.accept_redirects=0
sysctl -w net.ipv4.conf.default.accept_redirects=0
sysctl -w net.ipv4.conf.all.secure_redirects=0
sysctl -w net.ipv4.conf.default.secure_redirects=0
sysctl -w net.ipv4.conf.all.log_martians=1
sysctl -w net.ipv4.conf.default.log_martians=1
sysctl -w net.ipv4.icmp_echo_ignore_broadcasts=1
sysctl -w net.ipv4.icmp_ignore_bogus_error_responses=1
sysctl -w net.ipv4.conf.all.rp_filter=1
sysctl -w net.ipv4.conf.default.rp_filter=1
sysctl -w net.ipv4.tcp_syncookies=1
sysctl -w net.ipv4.route.flush=1
sysctl -w net.ipv6.conf.all.accept_ra=0
sysctl -w net.ipv6.conf.default.accept_ra=0
sysctl -w net.ipv6.conf.all.accept_redirects=0
sysctl -w net.ipv6.conf.default.accept_redirects=0
sysctl -w net.ipv6.route.flush=1
sed -i 's/GRUB_CMDLINE_LINUX=\"\"/GRUB_CMDLINE_LINUX=\"ipv6.disable=1 audit=1\"/g' /etc/default/grub
update-grub

# tcp wrappers
apt install tcpd -y

# hosts allow / deny
#echo "ALL: 192.168.1.0/255.255.255.0" | tee -a /etc/hosts.allow
echo "ALL: 192.168.1.0/255.255.255.0" >> /etc/hosts.allow
echo "ALL: ALL" >> /etc/hosts.deny
chown root:root /etc/hosts.allow
chmod 644 /etc/hosts.allow
chown root:root /etc/hosts.deny
chmod 644 /etc/hosts.deny

# iptables
apt install iptables -y
echo "IPTABLES FOR EACH NODE" >> /etc/iptables.conf
#example
#echo "# Generated by iptables-save v1.6.0 on Thu May  4 14:29:29 2017
#*filter
#:INPUT DROP [0:0]
#:FORWARD DROP [0:0]
#:OUTPUT DROP [0:0]
#-A INPUT -i lo -j ACCEPT
#-A OUTPUT -o lo -j ACCEPT
#-A INPUT -p udp -m state --state ESTABLISHED -j ACCEPT
#-A INPUT -p tcp -m state --state ESTABLISHED -j ACCEPT
#-A OUTPUT -p udp -m state --state NEW,ESTABLISHED -j ACCEPT
#-A OUTPUT -p tcp -m state --state NEW,ESTABLISHED -j ACCEPT
#-A INPUT -p tcp -m tcp --dport 443 -m state --state NEW -j ACCEPT
#-A INPUT -p tcp -m tcp --dport 123 -m state --state NEW -j ACCEPT
#-A INPUT -s 127.0.0.1/32 -d 127.0.0.1/32 -p tcp -m tcp --dport 3306 -j ACCEPT
#-A INPUT -s 127.0.0.1/32 -d 127.0.0.1/32 -p tcp -m tcp --dport 25 -j ACCEPT
#-A INPUT -s 192.168.56.0/24 -d 192.168.56.0/24 -p tcp -m tcp --dport 22 -j ACCEPT
#-A INPUT -s 192.168.56.0/24 -d 192.168.56.0/24 -p tcp -m tcp --dport 24007 -j ACCEPT
#-A INPUT -s 192.168.56.0/24 -d 192.168.56.0/24 -p udp -m udp --dport 68 -j ACCEPT
#COMMIT
# Completed on Thu May  4 14:29:29 2017
#" >> /etc/iptables.conf

iptables-save > /etc/iptables.conf
echo -ne "\npre-up iptables-restore < /etc/iptables.conf\n" >> /etc/network/interfaces 

exit 0
